- name: Add Sublime Text GPG key
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add Sublime Text apt repository
  become: yes
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present

- name: Update APT package cache
  become: yes
  apt:
    update_cache: yes

- name: Install required packages for mitm6
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Install mitm6 via pip
  become: yes
  pip:
    name: mitm6

- name: Install Tools
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - sublime-text
    - gobuster
    - seclists
    - ltrace
    - html2text
    - jq
    - gh
    - rsh-client
    - flameshot
    - xclip